#-------------------------------
# Site Settings
title: Nicholas Zollinger
logo: "/assets/Logo Black.png" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/assets/Logo White.png"
description: Nicholas Zollinger, Software Engineer in Games
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the users can choose the light or dark mode themself.
about_image: "/assets/Art/OnePieceProfilePic.png"

#-------------------------------
# Resume Settings
resume:
  link: "/assets/Resume.pdf"
  downloadName: "NicholasZollinger_Resume.txt"

#-------------------------------
# Author Settings
author_name: Aaron Simons

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    #- title: "Projects"
    #  url: "/projects/"
    - title: "Contact"
      url: "/contact/"

#-------------------------------
# Social Settings
social_professional:
- {icon: "fa-brands fa-github", link: "https://github.com/nicholaszollinger"}
- {icon: "fa-brands fa-linkedin", link: "https://www.linkedin.com/in/nicholas-zollinger/"}

social:
- {icon: "fa-brands fa-bluesky", link: "https://bsky.app/profile/nui-z.bsky.social"}


# Example of adding a new link to the header and footer - {icon: "fa-brands fa-youtube", link: "https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Programmer, Artist, <span><i>Nerd.</i></span> # Add the "span" tag to highlight text.
  hero_description: I’m Nick, a Gameplay Engineer in training based in the Bay Area. 
  hero_image: "/assets/Art/World Serpent Mountains.png"
  hero_button_contact: Get In Touch
  hero_button_about: About Me


#-------------------------------
# Projects Settings
section_projects_title: Projects

#-------------------------------
# Footer Settings
footer_description: Nicholas Zollinger, Software Engineer in Games

#-------------------------------
# Footer Navigation Settings
footer_menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    #- title: "Projects"
    #  url: "/projects/"
    - url: "/contact/"
      title: "Contact"


#-------------------------------
# Contact Settings
contact:
  email: nicholas.zollinger+work@protonmail.com

#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id