#-------------------------------
# Site Settings
title: Nicholas Zollinger
logo: "/images/logo.svg" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/logo-dark.svg"
description: Nicholas Zollinger – 
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the users can choose the light or dark mode themself.


#-------------------------------
# Author Settings
author_name: Nicholas Zollinger

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Projects"
      url: "/projects/"
    - title: "Contact"
      - url: "/contact/"

#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-twitter", link: "https://twitter.com/n_zollinger"}
- {icon: "fa-brands fa-github", link: "https://github.com/nicholaszollinger"}

# Example of adding a new link to the header and footer - {icon: "fa-brands fa-youtube", link: "https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Nicholas Zollinger. Programmer, Artist, <span><i>Nerd.</i></span> # Add the "span" tag to highlight text.
  hero_description: I’m Nick, a gameplay programmer based in the Bay Area, CA. [More intro stuff]
  hero_image: "/images/01.jpg"
  hero_button_contact: Get In Touch
  hero_button_about: About Me


#-------------------------------
# Projects Settings
section_projects_title: 👨🏻‍💻 Projects at a Glance


#-------------------------------
# Footer Settings
footer_description: I’m Nick, [shorter description here]

#-------------------------------
# Footer Navigation Settings
footer_menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Projects"
      url: "/projects/"
    - url: "/blog/"
      title: "Blog"
    - url: "/contact/"
      title: "Contact"
    - url: "/elements/"
      title: "Elements"


#-------------------------------
# Contact Settings
#contact:
#  email: your@email.com # Add your form_id
#  description: Simpler comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Simpler theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
# disqus_identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id